- name: Create ssh tunnel user
  user:
    name: "{{ ssh_tunnel_server_user }}"
    state: present

- name: Authorize tunnel key
  authorized_key:
    user: "{{ ssh_tunnel_server_user }}"
    key: "{{ item }}"
  with_items: "{{ ssh_tunnel_server_authorized_keys }}"

- name: Set ssh server keepalive settings
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.option }}"
    line: "{{ item.option }} {{ item.value }}"
  with_items:
    - { option: ClientAliveInterval, value: "{{ ssh_tunnel_server_alive_interval|default(30) }}" }
    - { option: ClientAliveCountMax, value: "{{ ssh_tunnel_server_alive_count_max|default(2) }}" }
  when: ssh_tunnel_server_set_keepalive
  notify: Restart sshd
